---
extensions:
    koempf-show-attribute-codes-product:
        module: koempf-show-attribute-codes/main
        parent: pim-product-edit-form-secondary-actions
        targetZone: secondary-actions
        position: 110
